---
title: "shell_function"
author: "Amy R Hodgson"
date: "08/08/2019"
output: pdf_document
---

Necessary set up.

```{r setup}

library(GGIR)
library(zoo)

datadir <- "path_to_data_folder"

outputdir <- "path_to_output_folder"

studyname <- "Date_Name_Keyword"

loglocation <- "path_to_sleeplog"

nnights <- number_of_nights

```

A couple of optional arguments. Change eval to T if using these.

```{r additional, eval = F}

f0 <- 1 # File to start with (default = 1)
f1 <- 4 # File to finish with (default = number of files available)

```

Shell function.

```{r shell}
g.shell.GGIR(
             mode=c(1,2,3,4,5),
             datadir = datadir, 
             outputdir = outputdir,
             idloc = 2, 
             f0=f0, f1=f1,
             studyname = studyname, 
             #-------------------------------
             # Part 1: 
             # Key functions: reading file, auto-calibration, and extracting features. 
             # Stores derived features (aggregations) needed for the other parts. This 
             # is the time consuming part. Once this is done, parts 2-5 can be run (or 
             # re-run with different parameters in parts 2-5) relatively quickly.
             #-------------------------------
             do.enmo = TRUE,            do.anglez=TRUE,
             chunksize=1,                printsummary=TRUE,
             #-------------------------------
             # Part 2:
             # Key functions: Data quality analyses and low level description of 
             # signal features per day and per file.
             #-------------------------------
             strategy = 1,               ndayswindow=7,
             hrs.del.start = 0,          hrs.del.end = 0,
             maxdur = 9,                 includedaycrit = 16,
             winhr = c(5,10),
             qlevels = c(c(1380/1440),c(1410/1440)),
             qwindow=c(0,24),
             ilevels = c(seq(0,400,by=50),8000),
             mvpathreshold =c(100,120),
             bout.metric = 4,
             closedbout=FALSE,
             #-------------------------------
             # Part 3: 
             # Key functions: Estimation of sustained inactivity and sleep periods, 
             # needed for input to Part 4 for sleep detection
             #-------------------------------
             timethreshold= c(5),        anglethreshold=5,
             ignorenonwear = TRUE,
             #-------------------------------
             # Part 4: 
             # Key functions: Integrating sleep log (if available) with sleep detection
             # storing day and person specific summaries of sleep
             #-------------------------------
             excludefirstlast = FALSE, # exclude first and last night
             includenightcrit = 16,
             def.noc.sleep = c(), 
             loglocation= loglocation,
             outliers.only = FALSE, # set TRUE for outlier visualisation
             criterror = 4,
             relyonsleeplog = FALSE, sleeplogidnum = FALSE,
             colid=1, coln1=2,
             do.visual = TRUE,
             nnights = nnights,
             #-------------------------------
             # Part 5:
             # Key functions: Merging physical activity with sleep analyses.
             # Derives sleep and physical activity characteristics by re-using information 
             # derived in part 2, 3 and 4. Total time in intensity categories, the number 
             # of bouts, time spent in bouts and average acceleration is calculated.
             #-------------------------------
             threshold.lig = c(30), threshold.mod = c(100),  threshold.vig = c(400),
             boutcriter = 0.8,      boutcriter.in = 0.9,     boutcriter.lig = 0.8,
             boutcriter.mvpa = 0.8, boutdur.in = c(1,10,30), boutdur.lig = c(1,10),
             boutdur.mvpa = c(1),   timewindow = c("WW"),
             #-----------------------------------
             # Report generation
             # Key functions: Generating reports based on meta-data
             #-------------------------------
             do.report=c(2,4,5), visualreport=TRUE, 
             dofirstpage = TRUE, viewingwindow=1
             )
```
